Repository Miladepour/SyntaxSquad-Project-Kunji, pull requests merged in 2023-03, with the labels that each got.

#5 1b- Create user preferences form - Milad
  client/src/App.js
  client/src/components/UserForm.js
  client/src/components/form-data/formdata.js
  client/src/pages/user-preferences/UserPreferences.css
  client/src/pages/user-preferences/UserPreferences.js
  package-lock.json
  package.json
Labels: enhancement

#24 #20 - front-end-only NGO CRUD view
  client/src/App.js
  client/src/index.html
  client/src/pages/admin/NGOs.js
  client/src/pages/admin/components/BinIcon.js
  client/src/pages/admin/components/CreateNGO.js
  client/src/pages/admin/components/PenPaperIcon.js
  client/src/pages/admin/components/PlusIcon.js
  client/src/pages/admin/data/ngos.json
Labels: enhancement

#27 fix result page data mismatch
  client/src/components/form-data/formdata.js
Labels: bug

#37 30 adding user info to database
  client/src/components/UserForm.js
  client/src/pages/admin/NGOs.js
  package-lock.json
  package.json
  server/api.js
  server/app.js
  server/routes/user.js
  server/validations/UserValidation.js
Labels: help wanted

#41 #32 create home page
  client/src/App.js
  client/src/app.css
  client/src/assest/kunji-logo2.svg
  client/src/components/Footer.js
  client/src/components/Footer.module.css
  client/src/components/Header.js
  client/src/components/Hero.js
  client/src/components/Hero.module.css
  client/src/components/NavBar.js
  client/src/components/NavBar.module.css
  client/src/components/wrappers/WrapperAdmin.js
  client/src/components/wrappers/WrapperUser.js
  client/src/pages/admin/Admin.js
  client/src/pages/admin/UserView.css
  client/src/pages/admin/UserView.js
  client/src/pages/home/Home.css
  client/src/pages/home/Home.js
  client/src/pages/result/Result.css
  client/src/pages/result/Result.js
  client/src/pages/user-preferences/UserPreferences.css
Labels: enhancement

#65 localization
  client/src/components/Footer.js
  client/src/components/Hero.js
  client/src/components/NavBar.js
  client/src/components/UserForm.js
  client/src/index.js
  client/src/localization/i18n.js
  client/src/localization/translation-en.json
  client/src/localization/translation-hi.json
  client/src/pages/about/About.js
  client/src/pages/result/Result.js
  client/src/pages/result/ResultMobV.js
  client/src/pages/result/button/SendEmailButton.js
  client/src/pages/result/button/SendSMSButton.js
  client/src/pages/result/button/SendWhatsappButton.js
  client/src/pages/user-preferences/UserPreferences.js
  package-lock.json
  package.json
Labels: enhancement
